const developerConcept = [
    "Tip: Use closures for private variables in JavaScript.",
    "Remember: Async/Await makes code look synchronous!",
    "Arrow functions inherit 'this' from their surrounding scope.",
    "Debugging Tip: Use console.trace() to see the call stack.",
    "CSS Trick: Use 'rem' for responsive font sizes.",
    "HTML Tip: Use semantic tags for better accessibility and SEO.",
    "JavaScript Tip: Avoid using global variables; they can lead to conflicts.",
    "Version Control Tip: Commit often with clear messages.",
    "Git Reminder: Use branches to keep feature development isolated.",
    "React Tip: Use React.memo to optimize performance.",
    "TypeScript Tip: Always prefer 'unknown' over 'any' for type safety.",
    "Database Tip: Index frequently queried fields for faster lookups.",
    "Security Reminder: Never commit secrets to your code repository.",
    "Coding Tip: Break down functions to avoid long blocks of code.",
    "CSS Trick: Use flexbox or grid for responsive layouts.",
    "JavaScript Tip: Use '===', not '==', to avoid unexpected type coercion.",
    "HTML Tip: Use alt text for images to improve accessibility.",
    "Async Tip: Use Promise.all to run promises in parallel.",
    "React Tip: Use functional components and hooks for cleaner code.",
    "TypeScript Tip: Use interfaces over types for better extensibility.",
    "Node.js Tip: Use environment variables to store configuration.",
    "Version Control Tip: Avoid committing generated files.",
    "Git Reminder: Use .gitignore to exclude unnecessary files.",
    "JavaScript Tip: Use destructuring for cleaner code.",
    "CSS Trick: Use variables for consistent styling across your app.",
    "React Reminder: Keep components pure and avoid side effects.",
    "Database Tip: Normalize data to reduce redundancy.",
    "HTML Tip: Use buttons for actions, links for navigation.",
    "Coding Practice: Write tests to catch bugs early.",
    "Security Reminder: Sanitize user input to prevent injection attacks.",
    "React Tip: Use useEffect for side effects, not useLayoutEffect.",
    "Git Tip: Use git stash to temporarily save changes.",
    "CSS Tip: Use 'vh' and 'vw' for viewport-based dimensions.",
    "JavaScript Tip: Use array methods like map, filter, and reduce.",
    "Database Reminder: Backup your data regularly.",
    "Coding Practice: Refactor code to improve readability.",
    "Security Tip: Use HTTPS for secure data transmission.",
    "React Tip: Avoid inline styles; use CSS or styled-components.",
    "TypeScript Tip: Use enums to manage constants.",
    "Version Control Tip: Use tags to mark release versions.",
    "JavaScript Tip: Use Object.freeze to create immutable objects.",
    "CSS Trick: Use '::before' and '::after' for decorative elements.",
    "HTML Tip: Use labels with form elements for better UX.",
    "Database Tip: Use transactions to maintain data integrity.",
    "Coding Practice: Write meaningful comments, but not too many.",
    "Security Reminder: Use prepared statements for SQL queries.",
    "React Reminder: Avoid using refs to access DOM directly.",
    "JavaScript Tip: Use optional chaining (?.) to handle null values.",
    "CSS Trick: Use animations sparingly to avoid performance issues.",
    "HTML Tip: Use metadata to enhance SEO and sharing.",
    "TypeScript Tip: Use generics for flexible type definitions.",
    "Version Control Tip: Use merge requests for collaborative reviews.",
    "JavaScript Tip: Use template literals for dynamic strings.",
    "Coding Practice: Use meaningful variable names.",
    "Security Tip: Use content security policies to prevent XSS attacks.",
    "React Tip: Use Context API for global state management.",
    "Database Tip: Index foreign keys for faster joins.",
    "CSS Tip: Reset styles to maintain consistency across browsers.",
    "JavaScript Tip: Use async functions over callbacks for readability.",
    "HTML Reminder: Use the 'title' attribute for additional context.",
    "Coding Practice: Refactor large files into modules.",
    "Security Reminder: Rotate keys and tokens periodically.",
    "React Reminder: Pass only necessary props to components.",
    "Version Control Tip: Keep your master branch production-ready.",
    "Database Tip: Avoid using SELECT * in queries for efficiency.",
    "JavaScript Tip: Prefer const over let for immutability.",
    "CSS Trick: Use CSS Grid for complex layouts.",
    "HTML Tip: Use placeholder text sparingly for better UX.",
    "TypeScript Tip: Use 'readonly' to create immutable arrays.",
    "Security Tip: Use helmet in Express to set security headers.",
    "React Tip: Use lazy loading for performance optimization.",
    "Database Reminder: Optimize queries to reduce load times.",
    "JavaScript Tip: Avoid mutating arrays; use array methods instead.",
    "CSS Trick: Use em/rem units for consistent scaling.",
    "HTML Reminder: Use ARIA attributes for accessibility.",
    "TypeScript Tip: Use type guards for better type checking.",
    "Version Control Tip: Use git rebase to keep history clean.",
    "JavaScript Tip: Use sets to remove duplicate values.",
    "Security Reminder: Always validate user input on the server side.",
    "React Reminder: Avoid storing sensitive data in state.",
    "Coding Practice: Regularly update dependencies.",
    "CSS Trick: Use media queries for responsive design.",
    "HTML Tip: Use 'target=_blank' carefully to avoid security risks.",
    "TypeScript Tip: Use utility types like Partial and Pick.",
    "Version Control Tip: Use git bisect to locate bugs.",
    "JavaScript Tip: Use JSON.stringify() to debug objects easily.",
    "Database Tip: Use data constraints for validation.",
    "React Reminder: Avoid overusing Context API; prefer Redux for complex state.",
    "Coding Practice: Set up automated tests to catch regressions.",
    "Security Tip: Use bcrypt for secure password hashing.",
    "JavaScript Tip: Use async/await in try-catch blocks for error handling.",
    "CSS Trick: Use transition for smooth hover effects.",
    "HTML Tip: Use 'lang' attribute for multilingual support.",
    "React Tip: Use error boundaries to catch rendering errors.",
    "Database Reminder: Avoid locking rows unless necessary.",
    "Version Control Tip: Use git diff to review changes before committing.",
    "JavaScript Tip: Use destructuring in function parameters for clarity.",
    "CSS Trick: Use clip-path for unique shapes.",
    "TypeScript Tip: Use 'assertion functions' for better type inference.",
    "Coding Practice: Conduct code reviews for quality control.",
    "Security Reminder: Use strict Content Security Policy headers.",
    "JavaScript Tip: Use the rest parameter to handle variable arguments.",
    "React Reminder: Only memoize components that benefit from it.",
]

const quotes = [
    "Believe in yourself!",
    "Success is the sum of small efforts, repeated day-in and day-out.",
    "Dream big and dare to fail.",
    "The best way to predict the future is to create it.",
    "Don't watch the clock; do what it does. Keep going.",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
    "Stay positive, work hard, make it happen.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Your limitation—it's only your imagination.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Believe you can and you're halfway there.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Do something today that your future self will thank you for.",
    "Opportunities don't happen, you create them.",
    "Don't stop when you're tired. Stop when you're done.",
    "It always seems impossible until it's done.",
    "The secret of getting ahead is getting started.",
    "Don't wait for opportunity. Create it.",
    "You don't have to be great to start, but you have to start to be great.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "If you want something you’ve never had, you must be willing to do something you’ve never done.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Don’t wish it were easier; wish you were better.",
    "A journey of a thousand miles begins with a single step.",
    "Success doesn’t just find you. You have to go out and get it.",
    "If you’re going through hell, keep going.",
    "Little things make big days.",
    "Believe in your infinite potential. Your only limitations are those you set upon yourself.",
    "It’s not about how hard you hit. It’s about how hard you can get hit and keep moving forward.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Be stronger than your excuses.",
    "Dream it. Believe it. Build it.",
    "Success is not in what you have, but who you are.",
    "What we achieve inwardly will change outer reality.",
    "The only person you should try to be better than is the person you were yesterday.",
    "If you can dream it, you can do it.",
    "Strive for progress, not perfection.",
    "Small progress is still progress.",
    "Failure is the opportunity to begin again more intelligently.",
    "Don’t limit your challenges, challenge your limits.",
    "If you want to lift yourself up, lift up someone else.",
    "Great things take time; be patient.",
    "To succeed, you need to find something to hold on to, something to motivate you, something to inspire you.",
    "Success is where preparation and opportunity meet.",
    "Your dreams don’t work unless you do.",
    "A smooth sea never made a skilled sailor.",
    "Difficulties in life are intended to make us better, not bitter.",
    "Whatever you are, be a good one.",
    "Aim for the moon. If you miss, you may hit a star.",
    "The key to success is to focus on goals, not obstacles.",
    "Believe in the power of yet: I don’t know it... yet.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "You are never too old to set another goal or to dream a new dream.",
    "Hard work beats talent when talent doesn’t work hard.",
    "If you don't give up, you still have a chance.",
    "Don’t let yesterday take up too much of today.",
    "Quality is not an act; it is a habit.",
    "Mistakes are proof that you are trying.",
    "Hustle in silence and let your success make the noise.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You don’t have to be perfect to be amazing.",
    "Make today so awesome yesterday gets jealous.",
    "The harder you fall, the higher you bounce.",
    "Sometimes later becomes never. Do it now.",
    "Act as if what you do makes a difference. It does.",
    "Don't quit. Suffer now and live the rest of your life as a champion.",
    "Every accomplishment starts with the decision to try.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "Don’t count the days; make the days count.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "You are capable of amazing things.",
    "No pressure, no diamonds.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "With the new day comes new strength and new thoughts.",
    "Don’t let the fear of losing be greater than the excitement of winning.",
    "Never give up because great things take time.",
    "Success doesn’t come from what you do occasionally; it comes from what you do consistently.",
    "Doubt kills more dreams than failure ever will.",
    "There is no elevator to success; you have to take the stairs.",
    "Don’t stop until you’re proud.",
    "No matter how hard it gets, keep going.",
    "Be so good they can't ignore you.",
    "Focus on being productive instead of busy.",
    "Do the best you can until you know better. Then when you know better, do better.",
    "Your only limit is you.",
    "Every day is a chance to get better.",
    "Nothing worth having comes easy.",
    "Be a warrior, not a worrier.",
    "Keep your face always toward the sunshine, and shadows will fall behind you.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Difficult roads often lead to beautiful destinations.",
    "If you get tired, learn to rest, not to quit.",
    "Success is not about being the best. It’s about always getting better."
];

function getRandom(array) {
    return array[Math.floor(Math.random() * array.length)]
}

chrome.storage.sync.get("userType", (data) => {
    const message = document.createElement("div");
    message.style.position = "fixed";
    message.style.bottom = "10px";
    message.style.right = "10px";
    message.style.padding = "10px";
    message.style.backgroundColor = "#222";
    message.style.color = "#fff";
    message.style.borderRadius = "8px";
    message.style.zIndex = "1000";

    if (data.userType == "Developer") {
        message.innerHTML = getRandom(developerConcept)
    } else {
        message.innerHTML = getRandom(quotes)
    }

    document.body.appendChild(message);
})